services:
  - type: web
    name: your-service-name   # Name your service (can be anything)
    env: python
    buildCommand: "pip install -r requirements.txt"   # Command to install dependencies
    startCommand: "python app.py"  # Command to run the app (replace with your actual start command)
    runtime: python-3.10  # Specify the Python version to use
