services:
  - type: web
    name: Timbuktu Reader
    env: python
    buildCommand: "pip install -r requirements.txt"   # Command to install dependencies
    startCommand: "python app.py"  # Command to run the app (replace with your actual start command)
    runtime: python-3.11  # Specify the Python version to use
